### ISSUE TITLE
Quero entrar

### ISSUE THREAD

**Issue by joaovinicius** [vim-sc/quero-entrar#3]
**Nome**: <Joao Vinicius de Paula>
**Email**: <joaoviniciusdp@gmail.com>
**Cidade**: <Guarapuava-Pr>
**Link do .vimrc**: <https://github.com/joaovinicius/dotfiles/blob/master/init.vim>

**Comment by mrprompt** [comment]
@joaovinicius  dá uma olhada no README sobre as novas instruções por favor.

**Comment by joaovinicius** [comment]
blz, vlw
